version: '3.3'

services:

    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command:
        - "--cassandra.keyspace=jaeger_v1_dc1"
        - "--cassandra.servers=cassandra"
        - "--collector.zipkin.http-port=9411"
      ports:
        - "14269:14269"
        - "14268:14268"
        - "14267:14267"
        - "14250:14250"
        - "9411:9411"
      networks:
        - proxy_net

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: 
        - "--cassandra.keyspace=jaeger_v1_dc1"
        - "--cassandra.servers=cassandra"
      ports:
        - "16686:16686"
        - "16687:16687"
      networks:
        - proxy_net

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: 
        - "--reporter.grpc.host-port=jaeger-collector:14250"
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      networks:
        - proxy_net

    cassandra:
      image: cassandra:3.9
      networks:
        - proxy_net

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      networks:
        - proxy_net

    spark-dependencies:
      image: jaegertracing/spark-dependencies
      environment:
        STORAGE: "cassandra"
        CASSANDRA_KEYSPACE: "jaeger_v1_dc1"
        CASSANDRA_CONTACT_POINTS: "cassandra"
      networks:
        - proxy_net

networks:
  proxy_net:
    external: true