version: '3.3'

services:

    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command:
        - "--cassandra.keyspace=jaeger_v1_dc1"
        - "--cassandra.servers=cassandra"
        - "--collector.zipkin.http-port=9411"
      networks:
        - proxy_net

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: 
        - "--cassandra.keyspace=jaeger_v1_dc1"
        - "--cassandra.servers=cassandra"
      networks:
        - proxy_net
      deploy:
        mode: replicated
        labels:
          - "traefik.frontend.entryPoints=http"
          - "traefik.port=16686"
          - "traefik.backend=jaeger-query"
          - "traefik.frontend.rule=Host:jaeger-query.local"
          - "traefik.docker.network=proxy_net"

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: 
        - "--reporter.grpc.host-port=jaeger-collector:14250"
      networks:
        - proxy_net

    cassandra:
      image: cassandra:3.9
      networks:
        - proxy_net

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      networks:
        - proxy_net

    spark-dependencies:
      image: jaegertracing/spark-dependencies
      environment:
        STORAGE: "cassandra"
        CASSANDRA_KEYSPACE: "jaeger_v1_dc1"
        CASSANDRA_CONTACT_POINTS: "cassandra"
      networks:
        - proxy_net

networks:
  proxy_net:
    external: true