version: "3.4"

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:9.6
    networks:
      - proxy_net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - proxy_net
    environment:
      KONG_PG_HOST: kong-database
    deploy:
      restart_policy:
        condition: on-failure

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: kong:latest
    networks:
      - proxy_net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    deploy:
      mode: replicated
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=8000"
        - "traefik.backend=kong"
        - "traefik.frontend.rule=Host:kong.local"
        - "traefik.docker.network=proxy_net"
  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong@kong-database:5432/konga_db"
    networks:
      - proxy_net
    deploy:
      restart_policy:
        condition: on-failure

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    networks:
      - proxy_net
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_USER: kong
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      DB_DATABASE: konga_db
      NODE_ENV: production
    deploy:
      mode: replicated
      labels:
        - "traefik.frontend.entryPoints=http"
        - "traefik.port=1337"
        - "traefik.backend=konga"
        - "traefik.frontend.rule=Host:konga.local"
        - "traefik.docker.network=proxy_net"

      
networks:
  proxy_net:
    external: true