debug = false
logLevel = "ERROR"
InsecureSkipVerify = true

#[accessLog]
#  format = "json"

[traefikLog]
  format  = "json"

[ping]
  entryPoint = "http"

[api]
entryPoint = "traefik"
dashboard = true
debug = false

[api.statistics]
recentErrors = 10

[metrics]
    [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]

[docker]
watch = true
swarmmode = true
exposedByDefault = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8082"

[tracing]
  backend = "jaeger"
  serviceName = "traefik"
  spanNameLimit = 0
  [tracing.jaeger]
    samplingServerURL = "http://jaeger-agent:5778/sampling"
    samplingType = "const"
    samplingParam = 1.0
    localAgentHostPort = "jaeger-agent:6831"
    traceContextHeaderName = "uber-trace-id"